challenges/EzGrammar/config/routes.rb
Rails.application.routes.draw do
  get 'errors/file_not_found'
  get 'errors/unprocessable'
  get 'errors/internal_server_error'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users
  resources :check, only: [:index, :create]
  resources :resumes, only: [:index, :new, :create, :destroy]
  root "resumes#index"

  match "/404", to: "errors#file_not_found", via: :all
  match "/422", to: "errors#unprocessable", via: :all
  match "/500", to: "errors#internal_server_error", via: :all
end

challenges/EzGrammar/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

challenges/EzGrammar/app/models/resume.rb
class Resume < ApplicationRecord
   mount_uploader :attachment, AttachmentUploader # Tells rails to use this uploader for this model.
   validates :name, presence: true # Make sure the owner's name is present.
end

challenges/EzGrammar/app/models/secretttt.rb
class Secretttt < ApplicationRecord
end

challenges/EzGrammar/app/models/user.rb
class User < ApplicationRecord
	has_secure_password
end

challenges/EzGrammar/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
  include UsersHelper
  include ResumesHelper
  include CheckHelper
  
  before_action :require_login

  def require_login
  	unless logged_in?
  		redirect_to login_path
  	end
  end
end

challenges/EzGrammar/app/controllers/check_controller.rb
class CheckController < ApplicationController
	def index
		@resumes = Resume.all
		if params[:q].present?
			if params[:q].to_s.length<50
				@q=grammar_check params[:q]
				@f=''
			else
				@f='Your input is too long, try using uploaded file instead'
				@q=''
			end
		else
			@q=''
			@f=''
		end
	end

	def create
		if params[:link].present? && params[:signature].present?
			@link=Base64.decode64(params[:link])
            # we care about security very much, we discuss, and concluse that theirs character must not been in the URL, seems legit, so filter it!
            idx= @link=~ /\$|\`|\<|\{|\+|\||\.\.|\(|\-|\*|\&|\=|\,/i
			if !idx
				if hash_calc(@link)==params[:signature]
					@url="/#{@link}"
					@file_check=eval("process_help '#{@url}'")
				else
					@link=''
					@file_check=''
				end
			else
				@link=''
				@file_check=''
			end
		else
			@link=''
			@file_check=''
		end
	end
end

challenges/EzGrammar/app/controllers/errors_controller.rb
class ErrorsController < ApplicationController
  def file_not_found
  end

  def unprocessable
  end

  def internal_server_error
  end
end

challenges/EzGrammar/app/controllers/resumes_controller.rb
class ResumesController < ApplicationController
   def index
      if params[:type].present? && avoid_error(params[:type])
         type=params[:type]
      else
         type="ASC"
      end
      @resumes = Resume.all.where(user: current_user.name).order("`resumes`.`name` #{type}")
   end
   
   def new
      @resume = Resume.new
   end
   
   def create
      @resume = Resume.new(resume_params)
      @resume.user=@current_user.name
      if @resume.attachment.present?
         if @resume.save
            @resume.update_attributes(hashfile: hash_calc(create_valid_upload_link(@resume.attachment_url)) )
            redirect_to resumes_path, notice: "The resume #{@resume.name} has been uploaded."
         else
            render "new"
         end
      else
         render "new"
      end
   end
   
   def destroy
      @resume = Resume.where(user: current_user.name).find(params[:id])
      @resume.destroy
      redirect_to resumes_path, notice:  "The resume #{@resume.name} has been deleted."
   end
   
   private
      def resume_params
      params.require(:resume).permit(:name, :attachment)
   end
   
end

challenges/EzGrammar/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  skip_before_action :require_login, only: [:new, :create]
  
  def new
  end

  def create
  	user = User.find_by name: params[:session][:name].downcase
  	if user && user.authenticate(params[:session][:password])
  		flash[:success]="Login success"
  		log_in user
  		redirect_to users_path
  	else
  		flash[:danger]="Something Wrong"
  		render :new
  	end
  end

  def destroy
  	log_out
  	flash[:success]="You're Logged out"
  	redirect_to login_path
  end
end

challenges/EzGrammar/app/controllers/users_controller.rb
class UsersController < ApplicationController

	skip_before_action :require_login, only: [:new, :create]
	
	def index
	end

	def new
		redirect_to users_path if logged_in?
		@user=User.new
	end

	def create
		@user=User.new user_params
		if !User.exists?(name: params[:user][:name])
			@user.save
			flash[:success]="Register Success"
			redirect_to users_path
		else
			flash[:success]="Register Failed"
			render :new
		end
	end

	def show
		@user=User.find_by id: params[:id]
		redirect_to users_path if @current_user != @user
	end

	private
	def user_params
		params.require(:user).permit :name, :password, :password_confirmation
    end
end

challenges/EzGrammar/app/helpers/application_helper.rb
module ApplicationHelper
end

challenges/EzGrammar/app/helpers/check_helper.rb
module CheckHelper
	def process_help url
		begin
			@file_check=File.open(url).read
			if File.size(url)<200
				@file_check=grammar_check @file_check
				return @file_check
			else
				return "Too large"
			end
		rescue
			exit("Something Wrong")
			return 0
		end
	end
end

challenges/EzGrammar/app/helpers/errors_helper.rb
module ErrorsHelper
end

challenges/EzGrammar/app/helpers/resumes_helper.rb
module ResumesHelper
	def hash_calc filepath
			pepper='V3Ry_Pr1v4t3@tsu' # Sorry, can't give you this
			salt=Secretttt.first.thinkoutoftheboxsmileicon
			# see why we are doing this: https://security.stackexchange.com/questions/3272/password-hashing-add-salt-pepper-or-is-salt-enough 
			return Digest::SHA1.hexdigest(pepper+filepath+salt).to_s
	end

	def create_valid_upload_link filepath
		return filepath[1..-1]
	end

	def avoid_error input_string
		idx= input_string=~ /\~|\`|\!|\@|\#|\$|\%|\^|\&|\*|\-|\_|\+|\=|\[|\]|\{|\}|\:|\;|\'|\"|\<|\>|\,|\.|\?|\/|\|/
		if !idx
			return true
		else
			return false
		end
	end
end

challenges/EzGrammar/app/helpers/sessions_helper.rb
module SessionsHelper
	def log_in user
		session[:user_id]=user.id
	end

	def log_out 
		session.delete :user_id
	end

	def current_user
		@current_user ||= User.find_by id: session[:user_id]
	end

	def logged_in?
		current_user.present?
	end
end

challenges/EzGrammar/app/helpers/users_helper.rb
module UsersHelper
	def grammar_check word
		begin
			parser = Gingerice::Parser.new
			result = parser.parse word
			return result['result']
		rescue
			return 'Something Wrong'
		end
	end
end

challenges/EzGrammar/app/views/check/create.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-12 text-center">
      <h1 class="title">Grammar Checker Service</h1>
    </div>
    <div class="col-lg-12 form-group text-center">
      <label for="">Welcome</label>
      <%= current_user.name %> -
      <span class="glyphicon glyphicon-user"></span>
      <%= link_to "Home", users_path, method: :get %> -
      <span class="glyphicon glyphicon-education"></span>
      <%= link_to "Check", check_index_path, method: :get %> -
      <span class="glyphicon glyphicon-upload"></span>
      <%= link_to "Upload", resumes_path, method: :get %> -
      <span class="glyphicon glyphicon-off"></span>
      <%= link_to "Logout", logout_path, method: :delete %>
    </div>
  </div>
<br>
<center><img src="assets/usagy-check.gif" width=20% height=20% /></center>
<br>
<div class="text-center bg-success"><%= @file_check.html_safe %></div>
<br>
<div class="panel panel-primary">
  <div class="panel-heading">Fast check</div>
  <div class="panel-body">
	<div class="text-center">
	<%= form_tag("/check", method: "get") do %>
	  <%= label_tag(:q, "") %>
	  <div class="form-group">
	  <%= text_field_tag :q, nil, class: "form-control" %>
	  </div>
	  <%= submit_tag "Check", class: "btn btn-primary" %>
	<% end %>
	</div>
  </div>
</div>
<br><br>
<div class="panel panel-info">
  <div class="panel-heading">Load from System</div>
  <div class="panel-body">
	<div class="text-center">
	<%= form_tag("/check", method: "post") do %>
	  <%= label_tag(:link, "Input") %>
	  <%= text_field_tag :link, nil, class: "form-control" %>
	  <br>
	  <%= label_tag(:signature,"Hash") %>
	  <%= text_field_tag :signature, nil, class: "form-control" %>
	  <br>
	  <%= submit_tag "Check", class: "btn btn-info" %>
	</div>
	<% end %>
	</div>
  </div>
</div>

challenges/EzGrammar/app/views/check/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-12 text-center">
      <h1 class="title">Grammar Checker Service</h1>
    </div>
    <div class="col-lg-12 form-group text-center">
      <label for="">Welcome</label>
      <%= current_user.name %> -
      <span class="glyphicon glyphicon-user"></span>
      <%= link_to "Home", users_path, method: :get %> -
      <span class="glyphicon glyphicon-education"></span>
      <%= link_to "Check", check_index_path, method: :get %> -
      <span class="glyphicon glyphicon-upload"></span>
      <%= link_to "Upload", resumes_path, method: :get %> -
      <span class="glyphicon glyphicon-off"></span>
      <%= link_to "Logout", logout_path, method: :delete %>
    </div>
  </div>
<br>
<center><img src="assets/usagy-check.gif" width=20% height=20% /></center>
<br>
<div class="text-center bg-success"><%=  @q.html_safe %></div>
<div class="text-center bg-danger"><%=  @f.html_safe %></div>
<br>
<div class="panel panel-primary">
  <div class="panel-heading">Fast check</div>
  <div class="panel-body">
	<div class="text-center">
	<%= form_tag("/check", method: "get") do %>
	  <%= label_tag(:q, "") %>
	  <div class="form-group">
	  <%= text_field_tag :q, nil, class: "form-control" %>
	  </div>
	  <%= submit_tag "Check", class: "btn btn-primary" %>
	<% end %>
	</div>
  </div>
</div>
<br><br>
<div class="panel panel-info">
  <div class="panel-heading">Load from System</div>
  <div class="panel-body">
	<div class="text-center">
	<%= form_tag("/check", method: "post") do %>
	  <%= label_tag(:link, "Input") %>
	  <%= text_field_tag :link, nil, class: "form-control" %>
	  <br>
	  <%= label_tag(:signature,"Hash") %>
	  <%= text_field_tag :signature, nil, class: "form-control" %>
	  <br>
	  <%= submit_tag "Check", class: "btn btn-info" %>
	</div>
	<% end %>
	</div>
  </div>
</div>

challenges/EzGrammar/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EzGrammar</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <section class="content" style="min-height: auto;">
      <% flash.each do |key, value| %>
        <div class="row">
          
    
          </div>
        </div>
      <% end %>
    </section>
    <%= yield %>
  </body>
</html>

challenges/EzGrammar/app/views/resumes/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-12 text-center">
      <h1 class="title">Grammar Checker Service</h1>
    </div>
    <div class="col-lg-12 form-group text-center">
      <label for="">Welcome</label>
      <%= current_user.name %> -
      <span class="glyphicon glyphicon-user"></span>
      <%= link_to "Home", users_path, method: :get %> -
      <span class="glyphicon glyphicon-education"></span>
      <%= link_to "Check", check_index_path, method: :get %> -
      <span class="glyphicon glyphicon-upload"></span>
      <%= link_to "Upload", resumes_path, method: :get %> -
      <span class="glyphicon glyphicon-off"></span>
      <%= link_to "Logout", logout_path, method: :delete %>
    </div>
  </div>
<% if !flash[:notice].blank? %>
   <div class = "alert alert-info">
      <%= flash[:notice] %>
   </div>
<% end %>

<br />
<center><img src="assets/usagy-upload.gif" width=20% height=20% /></center>
<center><%= link_to "New File", new_resume_path, class: "btn btn-primary" %></center>
<br />
<br />

<table class = "table table-bordered table-striped">
   <thead>.
      <tr>
         <th>Note</th>
         <th>Action</th>
         <th>File's Input</th>
         <th>File's Hash</th>
      </tr>
   </thead>
   
   <tbody>
      <% @resumes.each do |resume| %>
         
         <tr>
            <td><%= resume.name %></td>
            <td>
               <div class="btn-group">
                  <%= button_to "Check Grammar", {:controller => "check", :action => "create", :link => Base64.encode64(resume.attachment_url[1..-1]).strip, :signature => resume.hashfile} , :method=>:post, class: "btn btn-success", form: {target: '_blank'}  %> <%= button_to "Destroy This File",  resume, method: :delete, class: "btn btn-danger", confirm: "Are you sure that you wish to delete #{resume.name}?" %>
               </div>
            </td>
            <td><%= Base64.encode64(resume.attachment_url[1..-1]).strip %></td>
            <td><%= resume.hashfile %></td>
         </tr>
         
      <% end %>
   </tbody>
</table>
<div class="col-lg-12 form-group text-center">
</div>

challenges/EzGrammar/app/views/resumes/new.html.erb
<% if !@resume.errors.empty? %>
   <div class = "alert alert-error">
      
      <ul>
         <% @resume.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
         <% end %>
      </ul>
      
   </div>
<% end %>

<div class = "well">
   <%= form_for @resume, html: { multipart: true } do |f| %>
      <%= f.label :name, "Note" %>
      <%= f.text_field :name %>
      <%= f.label :attachment,"~" %>
      <%= f.file_field :attachment %>
      <%= f.submit "Save", class: "btn btn-primary" %>
   <% end %>
</div>

challenges/EzGrammar/app/views/users/index.html.erb
<style>
.rainbow {
  margin: 50px auto;
  text-align: center;
   /* Chrome, Safari, Opera */
  -webkit-animation: rainbow 1s infinite; 
  
  /* Internet Explorer */
  -ms-animation: rainbow 1s infinite;
  
  /* Standar Syntax */
  animation: rainbow 1s infinite; 
  font: normal 30px/normal "Warnes", Helvetica, arial;

}

/* Chrome, Safari, Opera */
@-webkit-keyframes rainbow{
  20%{color: red;}
  40%{color: yellow;}
  60%{color: green;}
  80%{color: blue;}
  100%{color: orange;}  
}
/* Internet Explorer */
@-ms-keyframes rainbow{
  20%{color: red;}
  40%{color: yellow;}
  60%{color: green;}
  80%{color: blue;}
  100%{color: orange;}  
}

/* Standar Syntax */
@keyframes rainbow{
  20%{color: red;}
  40%{color: yellow;}
  60%{color: green;}
  80%{color: blue;}
  100%{color: orange;}  
}
</style>

<div class="container">
  <div class="row">
    <div class="col-lg-12 text-center">
      <h1 class="title">Grammar Checker Service</h1>
    </div>
    <div class="col-lg-12 form-group text-center">
      <label for="">Welcome</label>
      <%= current_user.name %> -
      <span class="glyphicon glyphicon-user"></span>
      <%= link_to "Home", users_path, method: :get %> -
      <span class="glyphicon glyphicon-education"></span>
      <%= link_to "Check", check_index_path, method: :get %> -
      <span class="glyphicon glyphicon-upload"></span>
      <%= link_to "Upload", resumes_path, method: :get %> -
      <span class="glyphicon glyphicon-off"></span>
      <%= link_to "Logout", logout_path, method: :delete %>
    </div>
  </div>
  <br><br><br>
	<div class="text-center">
	<div class="rainbow">This is Awesome Grammar Checker Service, Feel free to use it...
	</div>
</div>
<center><img src="assets/usagy-default.gif" width=20% height=20% /></center>
</div>

challenges/EzGrammar/app/views/users/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-12 text-center">
      <h1 class="title">Register</h1>
    </div>
    <div class="col-lg-12 form-group text-center">
    </div>
  </div>
</div>
<div class="row">
  <div class="col-lg-offset-2">
    <%= form_for @user, html: {class: "form-horizontal"} do |f| %>
      <div class="form-group">
        <%= f.label :name, "Name", class: "col-md-2 control-label" %>
        <div class="col-md-6">
          <%= f.text_field :name, class: "form-control", placeholder: "Enter user name" %>
        </div>
      </div>
      <div class="form-group">
        <%= f.label :password, "Password", class: "col-md-2 control-label" %>
        <div class="col-md-6">
          <%= f.password_field :password, class: "form-control", placeholder: "Enter password" %>
        </div>
      </div>
      <div class="form-group">
        <%= f.label :password_confirmation, "Password Confirmation", class: "col-md-2 control-label" %>
        <div class="col-md-6">
          <%= f.password_field :password_confirmation, class: "form-control", placeholder: "Enter password confirmation" %>
        </div>
      </div>
      <div class="form-group">
        <div class="col-lg-offset-4">
          <%= f.submit "Register", class: "btn btn-success" %>
        </div>
      </div>
    <% end %>
    <% if !flash[:success].blank? %>
    <div class = "alert alert-info">
      <%= flash[:success] %>
    </div>
    <% end %>
  </div>
</div>